lib/jazz_web/router.ex
defmodule JazzWeb.Router do
  use JazzWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BasicAuth, use_config: {:basic_auth, :credentials}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", JazzWeb do
    pipe_through :browser

    get "/", PostController, :index
    get "/notes", NoteController, :index
    get "/notes/view", NoteController, :view
    get "/notes/edit", NoteController, :edit
    get "/notes/new", NoteController, :new
    post "/notes/create", NoteController, :create
    post "/notes/edit", NoteController, :save
    get "/notes/git_diff", NoteController, :git_diff
    post "/notes/git_add_commit", NoteController, :git_add_commit
    post "/notes/git_pull", NoteController, :git_pull
    post "/notes/git_push", NoteController, :git_push

    resources "/feeds", FeedController
    post "/feeds/preview", FeedController, :preview

    get "/posts/read", PostController, :show
    get "/posts/saved", PostController, :saved
    get "/posts/podcasts", PostController, :podcasts
    get "/posts/set_read", PostController, :set_read
    get "/posts/toggle_saved", PostController, :toggle_saved
    get "/posts/toggle_podcast", PostController, :toggle_podcast
    post "/posts/all_read", PostController, :all_read

    resources "/links", LinkController, only: [:index, :create]
    get "/links/delete/:id", LinkController, :delete
    get "/links/edit/:id", LinkController, :edit
    post "/links/edit/:id", LinkController, :save
  end

  # Other scopes may use custom stacks.
  # scope "/api", JazzWeb do
  #   pipe_through :api
  # end
end

lib/jazz_web/views/layout_view.ex
defmodule JazzWeb.LayoutView do
  use JazzWeb, :view
end

lib/jazz_web/templates/layout/app.html.eex
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= @page %></title>
    <link rel=icon href="data:;base64,=">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <nav role="navigation">
      <div class=logo>♪ Jazz</div>
      <%= if @page == "unread" do %>
        <%= link "Unread", to: Routes.post_path(@conn, :index), tabindex: -1, class: "current" %>
      <% else %>
        <%= link "Unread", to: Routes.post_path(@conn, :index), tabindex: -1 %>
      <% end %>

      <%= if @page == "saved" do %>
        <%= link "Saved", to: Routes.post_path(@conn, :saved), tabindex: -1, class: "current" %>
      <% else %>
        <%= link "Saved", to: Routes.post_path(@conn, :saved), tabindex: -1 %>
      <% end %>

      <%= if @page == "podcasts" do %>
        <%= link "Podcasts", to: Routes.post_path(@conn, :podcasts), tabindex: -1, class: "current" %>
      <% else %>
        <%= link "Podcasts", to: Routes.post_path(@conn, :podcasts), tabindex: -1 %>
      <% end %>

      <%= if @page == "links" do %>
        <%= link "Links", to: Routes.link_path(@conn, :index), tabindex: -1, class: "current" %>
      <% else %>
        <%= link "Links", to: Routes.link_path(@conn, :index), tabindex: -1 %>
      <% end %>

      <%= if @page == "notes" do %>
        <%= link "Notes", to: Routes.note_path(@conn, :index), tabindex: -1, class: "current" %>
      <% else %>
        <%= link "Notes", to: Routes.note_path(@conn, :index), tabindex: -1 %>
      <% end %>

      <%= if @page == "feeds" do %>
        <%= link "Feeds", to: Routes.feed_path(@conn, :index), tabindex: -1, class: "current" %>
      <% else %>
        <%= link "Feeds", to: Routes.feed_path(@conn, :index), tabindex: -1 %>
      <% end %>
    </nav>
    <main>
      <p class="msg msg__info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="msg msg__error" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/phx.js") %>"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>